name: Testing
on: push

jobs:
  test_projects:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip instal --user django
        python manage.py test

